# Generated by Django 5.2.13 on 2026-04-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
