# Generated by Django 4.2.30 on 2026-04-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_alter_itineraire_id_alter_lieu_id_alter_voyage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude GPS', null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='lng',
            field=models.FloatField(blank=True, help_text='Longitude GPS', null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='ville',
            field=models.CharField(default='Marrakech', max_length=100),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='cout',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
