# Generated by Django 5.2.13 on 2026-04-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoris', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favori',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
